@baseUrl = http://127.0.0.1:3000

### Retrieve all statements about Japan
GET {{baseUrl}}/api/v1/statements?subject=japan
Accept: text/plain

### Retrieve all persons across the loaded knowledge base
GET {{baseUrl}}/api/v1/statements?predicate=isA&object=%23Person
Accept: text/plain

### Retrieve all statements about Frodo Baggins
GET {{baseUrl}}/api/v1/statements?subject=frodo_baggins
Accept: text/plain
